hetzner_lb:
  hosts:
    MYSERVER1:
      ansible_port: 22
      ansible_host: 10.0.0.2
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeychecking=no -o ProxyCommand="ssh -W %h:%p -q madmin@78.47.182.180"'

    MYSERVER2:
      ansible_port: 22
      ansible_host: 10.0.0.4
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: '-o StrictHostKeychecking=no -o ProxyCommand="ssh -W %h:%p -q madmin@78.47.182.180"'
