services:
  traefik:
    image: traefik:v3.1.5

    container_name: traefik

    command:
      # Create an entrypoints "http" and "https"
      - --entrypoints.http.address=:80
      - --entryPoints.http.proxyProtocol.insecure
      - --entryPoints.http.forwardedHeaders.insecure

      # Create an entrypoint "https" listening on port 443
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Dynamic file providers
      - --providers.file
      - --providers.file.directory=/etc/traefikdyn
      # Enable the access log, with HTTP requests
      - --accesslog
      - --accesslog.filePath=/var/log/traefik/access.log
      # Enable the Traefik log, for configurations and errors
      - --log
      - --log.level=DEBUG
      # No Dashboard and API for now
      # - --api

    ports:
      - "80:80"

    labels:
      - "traefik.enable=true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynconfig/:/etc/traefikdyn/
      - ./log/:/var/log/traefik/

networks:
  default:
    name: service-network
    external: true
