# Inspired from https://github.com/5car1z/ansible-debian-provisioning
- name: "App Services Setup"
  hosts: all
  become: true
  gather_facts: yes

  vars_files:
    - vars/vars.yml

  tasks:
    # https://www.jeffgeerling.com/blog/2018/cloning-private-github-repositories-ansible-on-remote-server-through-ssh
    - name: "Clone Git Repo"
      become_user: "{{ my_admin_user }}"
      git:
        dest: "{{ my_git_home }}"
        repo: "{{ my_github_repo }}"
        clone: "yes"
        update: "yes"
        accept_hostkey: "yes"
        force: "yes"

    - name: "Build Docker Images"
      become_user: "{{ my_admin_user }}"
      shell: "cd {{ services_home }} && ./build.sh"

    # https://stackoverflow.com/questions/35984151/how-to-create-new-system-service-by-ansible-playbook
    - name: "Service | Create Unit file"
      template: src=templates/systemd.service.j2 dest=/lib/systemd/system/myservice.service mode=644

    - name: "reload systemctl"
      shell: "systemctl daemon-reload"
    
    - name: "Service | Start myservice"
      service: name=myservice.service state=started enabled=yes
