# Ansible workflow for single service deployment.
# Uses: https://github.com/dawidd6/action-ansible-playbook
# Options: https://github.com/dawidd6/action-ansible-playbook/blob/master/main.js
# Author: Just van den Broecke - 2024
#
name: MyApp Deploy ⚙️


# Trigger only when services/myapp subdir changed
on:
  workflow_dispatch:
    branches: [ main ]
  push:
    paths:
      - 'services/myapp/**'

jobs:
  main:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i hosts/prod.yml -t myapp --key-file private_key.pem -vvv deploy.yml
