# Ansible workflow for single service deployment.
# Uses: https://github.com/dawidd6/action-ansible-playbook
# Options: https://github.com/dawidd6/action-ansible-playbook/blob/master/main.js
# Author: Just van den Broecke - 2024
#
name: Traefik Deploy ⚙️

# Trigger only when services/traefik subdir changed
on:
  workflow_dispatch:
    branches: [ main ]
  push:
    paths:
      - 'services/traefik/**'

jobs:
  main:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Only way for ansible to pick up privkey file...
      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts/prod.yml -t traefik -v deploy.yml
