# Ansible workflow for single service deployment.
# Author: Just van den Broecke - 2024
#
name: Traefik Deploy ⚙️

# Trigger only when services/traefik subdir changed
on:
  workflow_dispatch:
    branches: [ main ]
  push:
    paths:
      - 'services/traefik/**'

jobs:
  main:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Only way for ansible to pick up privkey file...
      - name: Set up SSH and Ansible
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_pass.txt
          chmod 600 ~/.ssh/id_rsa ~/.vault_pass.txt 

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_VAULT_PASSWORD_FILE: ~/.vault_pass.txt
        run: |
          ansible-playbook -i hosts/prod.yml -t traefik -v deploy.yml
